### ISSUE TITLE
Possible typo in Chapter 5 supervision tree images?

### ISSUE THREAD

**Issue by Fadhil** [Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot#30]
In chapter 5, where we see an diagram representing the supervision tree, it seems like there is an error in `https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/tree/main/images/chapter_05_03_full.png`,`https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/tree/main/images/chapter_05_04_full.png` and `https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/tree/main/images/chapter_05_05_full.png`, 
where the bottom most `Naive.Leader` should actually read `Naive.Trader`. Otherwise, I might be understanding this wrong.

Related images: 

![chapter_05_03_leader_added](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/assets/170094/53ce906b-3459-4147-888f-1cd98f1781e2)
![chapter_05_04_symbol_sup](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/assets/170094/a5e5078b-a362-4297-8ff0-126d7bac4f9b)
![chapter_05_05_full](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/assets/170094/d26a6fac-5cfb-4229-8faf-6ed7e8a782cb)

**Comment by Cinderella-Man** [comment]
Hello @Fadhil,

Thank you very much for raising this issue. You are completely right and I'm truly surprised that nobody has pointed this out earlier - well done :+1:  - I will fix this as soon as I will figure out what app I was using to create those :thinking:

**Comment by Cinderella-Man** [comment]
Thank you once again - I built a new version of the book, updated online and on Gumroad - feel free to raise any other issues that you would came across - the power of the community :muscle: :rocket:
