### ISSUE TITLE
Unused Decimal Alias on chapter 10

### ISSUE THREAD

**Issue by Bodhert** [Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot#32]
Hello! I love your book 💟 !!! awesome work!

I believe that `alias Decimal` in [chapter 10](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/blob/664cd54534491778aa5afd0760467c24e8385f78/10-fine-tune-trading-strategy.Rmd#L351). serve no purpose

**Comment by Cinderella-Man** [comment]
Hello @Bodhert :wave: 

Apologies for so much lag in communication back to you. You are absolutely right - great attention to details :sunglasses: 

Thank you very much for your kind words about the book as well :heart: I hope that the remaining chapters of the book will take your appreciation/Elixir skill to a whole new level :rocket: All the best and thank you once again for raising an issue!

PS. The aliasing "improvement" will become part of the book in the next release - I just made a change to the source of the 10th chapter to not forget about it! Thank you! :pray:

**Comment by Bodhert** [comment]
@Cinderella-Man chapter 11 has the same detail in `/apps/streamer/priv/seed_settings.exs` 🙈

**Comment by Cinderella-Man** [comment]
Thank you once again - I fixed the issue in the 11th chapter and fixed the code in the source code repo - you are officially a "contributor" to my Elixir book - much appreciated :pray: 

![Release](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/assets/1019893/ba2ab4fa-69bd-47f3-995f-46fc0b49c9d7)
