### ISSUE TITLE
Typo on chapter_12_02_sup_diagram.png

### ISSUE THREAD

**Issue by Bodhert** [Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot#33]
its me with more typos 🙈 

<img width="412" alt="image" src="https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/assets/14171790/b20edf0d-2e08-4070-99d7-4aff22fd8ffd">

it should be autostart_trading

**Comment by Cinderella-Man** [comment]
You are great at spotting typos - eagle eyes :wink: I updated the book - thank you very much for raising the issue! :pray:
