### ISSUE TITLE
Typos/errors reading along with the book

### ISSUE THREAD

**Issue by Bodhert** [Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot#36]
Hello @Cinderella-Man! still enjoying the book 💟 

<img width="672" alt="image" src="https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/assets/14171790/afad4801-d644-46af-9bdb-637386cc7c8e">

maybe did you mean data?

**Comment by Bodhert** [comment]
Hello!
reading further more typos/errors

[I guess you maybe mean placed](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/blob/75bb8a4bedfe93aeb884a043dcfb400307bbd8aa/16-end-to-end-testing.Rmd#L129)
[same here](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/blob/75bb8a4bedfe93aeb884a043dcfb400307bbd8aa/16-end-to-end-testing.Rmd#L137)


you did [fix this in your source code](https://github.com/Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot/blob/75bb8a4bedfe93aeb884a043dcfb400307bbd8aa/16-end-to-end-testing.Rmd#L370) but not in the book, If we do a 'follow along reading' that will not work

**Comment by Cinderella-Man** [comment]
Hello @Bodhert :wave: 

Thank you for raising those issues - I've updated the book to version 0.6.0 - added two chapters and fixed all the problems you mentioned.

I really appreciate your help :pray:
